<?php

/*
 *  Copyright 2015-17 Baubadil GmbH. All rights reserved.
 */

namespace Doreen;


/*
 *  The prologue.php gets included from all three entry points (index.php, api/api.php, ../cli/cli.php)
 *  and contains global definitions that should always be present.
 *
 *  NOTE: class_globals.php must be included BEFORE THIS, and is in a separate file because the prologue
 *  contains some plugin magic to make the CLI work for multiple installations, and that magic occurs
 *  in between including class_globals.php first and then the prologue second.
 */


/********************************************************************
 *
 *  Global constants and variables
 *
 ********************************************************************/

# We run the update install if the 'config' table, 'database-version' key, has a smaller version than this.
const DATABASE_VERSION              = 93;
const USER_LOCALDB_VERSION          = 1;            # this must be here to fix botched install before v62

require INCLUDE_PATH_PREFIX.'/core/globalfuncs.php';
require INCLUDE_PATH_PREFIX.'/core/class_debug.php';
# Require the autoloader generated by PHP composer.
require INCLUDE_PATH_PREFIX.'/../vendor/autoload.php';

Globals::Init();

const DOREEN_DATA_DIR = '/var/lib/doreen';
const DOREEN_ATTACHMENTS_BASENAME = 'attachments';
const DOREEN_ATTACHMENTS_PARENT_DIR = DOREEN_DATA_DIR.'/'.DOREEN_ATTACHMENTS_BASENAME;

require INCLUDE_PATH_PREFIX.'/core/class_plugin.php';

# Start the session!
if (!IS_API)
    LoginSession::Secure();

require INCLUDE_PATH_PREFIX.'/core/class_locale.php';
DrnLocale::Init();

# We load the following classes always instead of via the autoloader.
require INCLUDE_PATH_PREFIX.'/core/class_user.php';
require INCLUDE_PATH_PREFIX.'/core/class_database.php';

# $g_aPlugins should be set in the optional vars file that gets written at install time.
$g_aPlugins = [];
@include Globals::$fnameOptionalVars;
$g_aPlugins[] = 'user_hardcoded';
$g_aPlugins[] = 'user_localdb';

Plugins::Init($g_aPlugins);

define('DEBUG_JSON_OUTPUT', JSON_PRETTY_PRINT); # JSON_PRETTY_PRINT);
